function formation(nom, tarif, pdf) {
    

    obj = {
        nom: nom, tarif: tarif, pdf:pdf
    }


    return obj

}



let tab = 
[

    formation("ANGLAIS A1/A2 VISO +E-LEARNING", 1800, "pdf/PROGRAMME DE FORMATION ANGLAIS A1A2 VISIO^ME-LEARNING.pdf"),
    formation("ANGLAIS B1/B2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION ANGLAIS B1B2 VISIO^ME-LEARNING.pdf"),
    formation("ANGLAIS C1/C2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION ANGLAIS C1C2 VISIO^ME-LEARNING-converti.pdf"),

    formation("FRANCAIS A1/A2 VISIO + E-LEARNING", 1800, "pdf/PROGRAMME DE FORMATION FRANCAIS A1A2 VISIO^ME-LEARNING-converti.pdf"),
    formation("FRANCAIS B1/B2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION FRANCAIS B1B2 VISIO^ME-LEARNING.pdf"),
    formation("FRANCAIS C1/C2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION FRANCAIS C1C2 VISIO^ME-LEARNING.pdf"),

    formation("ESPAGNOL A1/A2 VISIO + E-LEARNING", 1800, "pdf/PROGRAMME DE FORMATION ESPAGNOL A1A2 VISIO^ME-LEARNING.pdf"),
    formation("ESPAGNOL B1/B2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION ESPAGNOL B1B2 VISIO^ME-LEARNING.pdf"),
    formation("ESPAGNOL C1/C2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION ESPAGNOL C1C2 VISIO^ME-LEARNING.pdf"),
    
    formation("ALLEMAND A1/A2 VISIO + E-LEARNING", 1800, "pdf/PROGRAMME DE FORMATION ALLEMAND A1A2 VISIO^ME-LEARNING.pdf"),
    formation("ALLEMAND B1/B2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION ALLEMAND B1B2 VISIO^ME-LEARNING.pdf"),
    formation("ALLEMAND C1/C2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION ALLEMAND C1C2 VISIO^ME-LEARNING.pdf"),
    
    formation("ARABE A1/A2 VISIO + E-LEARNING", 1800, "pdf/PROGRAMME DE FORMATION ARABE A1A2 VISIO^ME-LEARNING.pdf"),
    formation("ARABE B1/B2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION ARABE B1B2 VISIO^ME-LEARNING.pdf"),
    formation("ARABE C1/C2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION ARABE C1C2 VISIO^ME-LEARNING.pdf"),
    
    formation("ITALIEN A1/A2 VISIO + E-LEARNING", 1800, "pdf/PROGRAMME DE FORMATION ITALIEN A1A2 VISIO^ME-LEARNING.pdf"),
    formation("ITALIEN B1/B2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION ITALIEN B1B2 VISIO^ME-LEARNING.pdf"),
    formation("ITALIEN C1/C2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION ITALIEN C1C2 VISIO^ME-LEARNING.pdf"),

    formation("MADARIN A1/A2 VISIO + E-LEARNING", 1800, "pdf/PROGRAMME DE FORMATION MADARIN A1A2 VISIO^ME-LEARNING.pdf"),
    formation("MADARIN B1/B2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION MADARIN B1B2 VISIO^ME-LEARNING.pdf"),
    formation("MADARIN C1/C2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION MADARIN C1C2 VISIO^ME-LEARNING.pdf"),

    formation("PORTUGAIS A1/A2 VISIO + E-LEARNING", 1800, "pdf/PROGRAMME DE FORMATION PORTUGAIS A1A2 VISIO^ME-LEARNING.pdf"),
    formation("PORTUGAIS B1/B2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION PORTUGAIS B1B2 VISIO^ME-LEARNING.pdf"),
    formation("PORTUGAIS C1/C2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION PORTUGAIS C1C2 VISIO^ME-LEARNING.pdf"),
    
    formation("RUSSE A1/A2 VISIO + E-LEARNING", 1800, "pdf/PROGRAMME DE FORMATION RUSSE A1A2 VISIO^ME-LEARNING.pdf"),
    formation("RUSSE B1/B2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION RUSSE B1B2 VISIO^ME-LEARNING.pdf"),
    formation("RUSSE C1/C2 VISIO + E-LEARNING", 2000, "pdf/PROGRAMME DE FORMATION RUSSE C1C2 VISIO^ME-LEARNING.pdf"),

    formation("BASES INFORMATIQUES", 1800, "pdf/PROGRAMME DE FORMATION BASES INFORMATIQUES VISIO^ME-LEARNING.pdf"),

    formation("PHOTOSHOP", 1800, "pdf/PROGRAMME DE FORMATION PHOTOSHOP VISIO^ME-LEARNING.pdf"),
    
    formation("INDESIGN", 1800, "pdf/PROGRAMME DE FORMATION INDESIGN VISIO^ME-LEARNING.pdf"),
    
    formation("ILLUSTRATOR", 1800, "pdf/PROGRAMME DE FORMATION ILLUSTRATOR VISIO^ME-LEARNING.pdf"),
    
    formation("AUTOCAD", 1800, "pdf/PROGRAMME DE FORMATION AUTOCAD VISIO^ME-LEARNING.pdf"),
    
    formation("WORDPRESS", 1800, "pdf/PROGRAMME DE FORMATION WORDPRESS VISIO^ME-LEARNING.pdf"),
    
    formation("DEVELOPPEMENT WEB", 2000, "pdf/PROGRAMME DE FORMATION DEVELOPPEMENT WEB VISIO.pdf"),

    formation("WORD DEBUTANT", 2000, "pdf/PROGRAMME DE FORMATION WORD DEBUTANT 2016 2019 VISIO^ME-LEARNING.pdf"),
    formation("WORD AVANCE", 2000, "pdf/PROGRAMME DE FORMATION WORD AVANCE 2016 2019 VISIO^ME-LEARNING.pdf"),

    formation("EXCEL DEBUTANT", 2000, "pdf/PROGRAMME DE FORMATION EXCEL DEBUTANT 2016 2019 VISIO^ME-LEARNING.pdf"),
    formation("EXCEL AVANCE", 2000, "pdf/PROGRAMME DE FORMATION EXCEL AVANCE 2016 2019 VISIO^ME-LEARNING.pdf"),

    formation("OUTLOOK DEBUTANT", 2000, "pdf/PROGRAMME DE FORMATION OUTLOOK DEBUTANT VISIO ^M E-LEARNING.pdf"),
    formation("OUTLOOK AVANCE", 2000, "pdf/PROGRAMME DE FORMATION OUTLOOK AVANCE VISIO ^M E-LEARNING.pdf"),

    formation("POWERPOINT DEBUTANT", 2000, "pdf\PROGRAMME DE FORMATION POWERPOINT DEBUTANT VISIO ^M E-LEARNING.pdf"),
    formation("POWERPOINT AVANCE", 2000, "pdf\PROGRAMME DE FORMATION POWERPOINT AVANCE VISIO ^M E-LEARNING.pdf")
]

